global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"

scrape_configs:
  # The job name is added as a label `job=<job_name>` to any timeseries scraped from this config.
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  # Belanova Gateway metrics
  - job_name: 'belanova-gateway'
    static_configs:
      - targets: ['gateway:8080']
    scrape_interval: 10s
    metrics_path: '/actuator/prometheus'
    params:
      format: ['prometheus']

  # Admin UI metrics
  - job_name: 'belanova-admin-ui'
    static_configs:
      - targets: ['admin-ui:8081']
    scrape_interval: 15s
    metrics_path: '/actuator/prometheus'
    params:
      format: ['prometheus']

  # PostgreSQL metrics (if available)
  - job_name: 'postgres'
    static_configs:
      - targets: ['postgres:5432']
    scrape_interval: 30s

  # Redis metrics
  - job_name: 'redis'
    static_configs:
      - targets: ['redis:6379']
    scrape_interval: 30s

  # Apache Ignite metrics
  - job_name: 'ignite'
    static_configs:
      - targets: ['ignite:49112']
    scrape_interval: 30s

  # Node exporter (if running on host)
  - job_name: 'node'
    static_configs:
      - targets: ['host.docker.internal:9100']
    scrape_interval: 30s